### ISSUE TITLE
NO GOOD DOCUMENTATION ABOUT API (wordpress) USAGE

### ISSUE THREAD

**Issue by hygull** [myles/python-wp#13]
The idea is too good to provide the users an interface to interact with the Wordpress data using APIs. 

To enable users to effectively use these services, there is no proper documentation so that it could minimize the time to explore about the APIs usage.

Today, I tried to install module in the following 2 ways but failed.

**1st way**
```bash
$ pip install wordpress
Collecting wordpress
  Could not find a version that satisfies the requirement wordpress (from versions: )
No matching distribution found for wordpress

rishikesh agrawani@DESKTOP-8AATOO4 MINGW64 /d/projects/Tasks/PyLaTex/wordpress-api/src
```

**2nd way**
```
$ pip install python-wp
Collecting python-wp
  Could not find a version that satisfies the requirement python-wp (from versions: )
No matching distribution found for python-wp
```

**Comment by myles** [comment]
Hi @hygull,

`python-wp` is still in the development stages and hasn't been released on PyPi yet so you can't just install it using `pip` yet.

If you would like you can install it using Git with `pip install git+https://github.com/myles/python-wp` but I wouldn't recommend it as the API might change down the line.

Documented at this stage is a huge undertaking for a project I maybe work on one to three hours a month.

When I'm confident that the code is stable and enough tests have been written then I will be releasing it on PyPi with documentation.

I'm sorry if this has caused any confusion, there are a lot more stable WordPress python libraries on PyPi right now, https://pypi.python.org/pypi?%3Aaction=search&term=wordpress&submit=search.

**Comment by hygull** [comment]
Okay @myles , no problem. Continue with your development and provide a good package that could enable us communicating with Wordpress REST APIs.

Thanks.
